apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-beans-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-beans-model
  template:
    metadata:
      labels:
        app: tf-serving-beans-model
    spec:
      containers:
      - name: tf-serving-beans-model
        image: 551011018709.dkr.ecr.us-west-1.amazonaws.com/tf-serving-img:beans-model-xception_final_model
        resources:
          limits:
            memory: "512Mi"
            cpu: "1024m"
        ports:
        - containerPort: 8500
